name: Mystira.App API CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'Mystira.App.Admin.Api/**'
      - 'Mystira.App.Api/**'
      - 'Mystira.App.Domain/**'
      - '.github/workflows/ci-cd.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Mystira.App.Admin.Api/**'
      - 'Mystira.App.Api/**'
      - 'Mystira.App.Domain/**'

env:
  DOTNET_VERSION: '9.0.x'
  AZURE_WEBAPP_NAME: 'prod-wus-app-mystira-api'
  AZURE_WEBAPP_PACKAGE_PATH: './publish'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Check code formatting
      run: dotnet format --verify-no-changes --verbosity diagnostic
    
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:EnforceCodeStyleInBuild=true
    
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
    
    - name: Publish
      run: dotnet publish Mystira.App.Api/Mystira.Api.csproj --configuration Release --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: mystira-app-api
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/develop'
    environment: development
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: mystira-app-api
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: Deploy to Azure Web App (Development)
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: mystira-app-api
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    
    - name: Deploy to Azure Web App (Production)
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'prod-wus-app-mystira-api'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  infrastructure:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[deploy-infra]')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Infrastructure
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: 'prod-wus-rg-mystira-app'
        template: './Mystira.App.Api/Infrastructure/Azure/main.bicep'
        parameters: 'environment=prod jwtSecretKey=${{ secrets.JWT_SECRET_KEY }}'